"""Pre-build step: gzip the portal's CSS and JS into a generated PROGMEM header.

The config page used to carry ~106 KB of inline CSS+JS inside PAGE_HTML. Served
as separate gzipped assets it costs ~26 KB of flash instead, which is the
difference between fitting on the 1.75 MB C3 app slot and not.

Nothing is decompressed on the device - the browser does that. Each asset's URL
carries a hash of its own bytes, so a firmware update can never leave a browser
holding a stale script for a page that has moved on.

Wired in from platformio.ini as `extra_scripts = pre:tools/gen_web_assets.py`.
"""
import gzip
import os
import zlib

Import("env")  # noqa: F821 - injected by PlatformIO/SCons

PROJECT_DIR = env.subst("$PROJECT_DIR")  # noqa: F821
BUILD_DIR = env.subst("$BUILD_DIR")  # noqa: F821
GEN_DIR = os.path.join(BUILD_DIR, "generated")
OUT = os.path.join(GEN_DIR, "web_assets_gz.h")

ASSETS = [
    ("WEB_APP_CSS", os.path.join(PROJECT_DIR, "web", "app.css")),
    ("WEB_APP_JS", os.path.join(PROJECT_DIR, "web", "app.js")),
]


def emit_array(name, raw):
    # mtime=0 keeps the output byte-identical across builds, so SCons only
    # rebuilds the web server when the asset itself actually changed.
    blob = gzip.compress(raw, compresslevel=9, mtime=0)
    version = format(zlib.crc32(raw) & 0xFFFFFFFF, "08x")

    lines = [f"static const uint8_t {name}_GZ[] PROGMEM = {{"]
    for i in range(0, len(blob), 16):
        chunk = blob[i:i + 16]
        lines.append("  " + "".join(f"0x{b:02x}," for b in chunk))
    lines.append("};")
    lines.append(f"static const size_t {name}_GZ_LEN = {len(blob)};")
    lines.append(f'#define {name}_VER "{version}"')
    lines.append("")
    return "\n".join(lines), len(raw), len(blob)


def main():
    os.makedirs(GEN_DIR, exist_ok=True)

    body = []
    report = []
    for name, path in ASSETS:
        if not os.path.isfile(path):
            raise Exception(f"gen_web_assets: missing asset {path}")
        with open(path, "rb") as fh:
            raw = fh.read()
        chunk, raw_len, gz_len = emit_array(name, raw)
        body.append(chunk)
        report.append(f"{os.path.basename(path)} {raw_len} -> {gz_len} B")

    header = (
        "// Generated by tools/gen_web_assets.py - do not edit, do not commit.\n"
        "// Source of truth: web/app.css and web/app.js.\n"
        "//\n"
        "// Included by exactly one translation unit (src/web_server.cpp); the\n"
        "// static storage class means every other includer would duplicate it.\n"
        "#pragma once\n"
        "#include <Arduino.h>\n"
        "#include <pgmspace.h>\n\n"
        + "\n".join(body)
    )

    previous = ""
    if os.path.isfile(OUT):
        with open(OUT, encoding="utf-8") as fh:
            previous = fh.read()
    if previous != header:
        with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(header)

    print("gen_web_assets: " + ", ".join(report))


main()
env.Append(CPPPATH=[GEN_DIR])  # noqa: F821
